---
include:
  - "**/*.rb"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
  - db/**/*
  - config/**/*
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
require_paths: []
max_files: 5000
